name: Deploy release build for production

on:
  # Triggers the workflow on push only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Bundle Update
        run: gem install bundler:1.17.2
      - name: Bundle Install
        run: bundle install
      - name: Install Pod Dependencies
        run: bundle exec pod install
      - name: Upload release build for production
        run: bundle exec fastlane production_release
        env:
          GIT_PRIVATE_KEY: '${{ secrets.GIT_PRIVATE_KEY }}'
